### PR TITLE
Added new config

### PR DESCRIPTION
**Pull request by atton16**
Hi,

I have added new config to make the library even more awesome.

I also added some tests, update readme and resolve reserved variable name, namely `package` to `_package`.

Please kindly review it and approve my PR.

If you do so, please also don't forget to patch the version and publish it to NPM.

Cheers!

### CODE REVIEW

**Comment by atton16** [comment]
Sorry, found some bugs. Will fix it first!

**Comment by atton16** [comment]
Looks good now!

**Comment by atton16** [comment]
Hi, I just found a bug that it omitted packages.access and packages.publish ACL. But no worries, I got it.

**Comment by CrispyConductor** [comment]
Thanks for the work!  Looks good - merged and published.

**Pull request merged**
