### PR TITLE
Search project

### PR DESCRIPTION
**Pull request by kolcak**
Better project search.
- build query from settings before call api (see: readme.md)
- api user without admin privileges
- ~~replace option 'gitlab_namespaces' with 'gitlab_namespace'~~

### CODE REVIEW

**Comment by confuser** [comment]
It appears you've removed the ability to have an array of namespaces within the config file? We're using that feature

**Comment by kolcak** [comment]
Can you write me use cases with namespaces? (example: package_name -> gitlab_path)
because current implementation have bug, if namespaces are disabled and don't work effective

**Comment by confuser** [comment]
We have projects in multiple namespaces, e.g. package1 -> namespace1/package1, package2 -> namespace2/package2

**Comment by kolcak** [comment]
thx .. look it, maybe tonight

**Comment by kolcak** [comment]
Hi,
- back supported namespaces ;)

**Pull request merged**
